### ISSUE TITLE
[Question] Can I generate pdf without save in my phone?

### ISSUE THREAD

**Issue by BogdanRad** [Canciller/react-native-images-to-pdf#1]
Hello @Canciller,

I use this package https://github.com/websitebeaver/react-native-document-scanner-plugin for scan my medical documents. If I have multiple photos after scanned I want to generate a pdf with them and send it to the server.. Could I do this with your package without generating a local pdf?

Thank you and have nice day!

**Comment by Canciller** [comment]
Hi, currently my package only supports saving pdfs locally, not direct server upload. However, you could upload the local file to your server and then delete it.

**Comment by sufita** [comment]
How about base64 image? will you provide that feature? 
If so, we can use this lib without saving it to local or upload it to server as you said.
