### ISSUE TITLE
[QUESTION] How to save this pdf file to Android local storage

### ISSUE THREAD

**Issue by rezamohdev** [Canciller/react-native-images-to-pdf#10]
Hi, thanks for publishing this useful package,
**How I can save this pdf to local storage in Android?**
My problem is that I don't know how i can get this part:
` outputPath: '/path/to/output/file.pdf',`
 Do I should use Blob or Fs react  native?
 of course I have to mention that I use `    "react-native-document-scanner-plugin": "^0.9.0",`
 and I have a single uri that is generated by this plugin so I have the input path

**Comment by Canciller** [comment]
I use [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util/wiki/File-System-Access-API#dirs), but the libraries you mentioned work too.

**Comment by Canciller** [comment]
https://github.com/Canciller/react-native-images-to-pdf/blob/96e392f6c9181a9450c4a6acef98434e6b444c97/example/src/App.tsx#L70
