### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by velevtzvetlin** [Canciller/react-native-images-to-pdf#16]
## Summary

- Images taken in portrait mode on android
- images passed to createPdf
- pdf viewed on device and images appear to be rotated

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. Expected similar result as ios (images in portrait mode => rendered in portrait mode in pdf)
2. …

## Environment info

`npx react-native info` output:

library version: 0.2.0

iOS / Android version: x.x

**Comment by velevtzvetlin** [comment]
![Screenshot 2023-09-05 at 10 32 42 AM](https://github.com/Canciller/react-native-images-to-pdf/assets/10441720/21b7499e-f5e1-415f-9180-aee09271f389)

**Comment by Canciller** [comment]
Please create a small repository demonstrating the issue. This will help me in fixing the problem.
