### ISSUE TITLE
Uri to display and send to server

### ISSUE THREAD

**Issue by nolife08021** [Canciller/react-native-images-to-pdf#6]
Hi, how do i use the uri return from createPdf  to display it in react-native-pdf and use the path and send to server.
I try add "file://", is not working. 

res i get from createPdf
"/tree/primary:Documents/document/primary:Documents/594w-842h-contain (9).pdf"

**Comment by Canciller** [comment]
is this in android or ios?

**Comment by Canciller** [comment]
Fixed with latest version.

**Comment by nolife08021** [comment]
Is on android
