### ISSUE TITLE
There was a failure while populating the build operation queue: Failed to create MD5 hash for file content.

### ISSUE THREAD

**Issue by muhammadashariabdillah24** [Canciller/react-native-images-to-pdf#9]
"react-native-image-to-pdf": "^1.2.0",

When i running use yarn android, i get this error

![Screenshot 2023-08-09 115211](https://github.com/Canciller/react-native-images-to-pdf/assets/84664072/259b4d7f-6641-4f3d-8f54-a16e20454356)

**Comment by Canciller** [comment]
That is not this package.
